### ISSUE TITLE
Default Settings Incorrect

### ISSUE THREAD

**Issue by Rugbeo** [Synthian/LiveSplit.Bastion#1]
Hello!

If you are using the splits from the current WR, the autosplitter will split at "Wharf District" when you leave the watering hole and land on the breaker's bow.

To get around this issue I have added a new split "Watering Hole" before "Wharf District", but it may be something you want to look in to.

Thank you!

**Comment by Synthian** [comment]
This is an option in the settings. In the Layout Settings, you have these options:
![](http://puu.sh/tosMi/ec6159d37e.png)  

The level is called The Sole Regret. It should only split after the Sole Regret if you have that option checked. Is that the case? It should have been off by default, do you know if you changed it?

**Comment by Rugbeo** [comment]
Thanks for your reply!

I haven't modified any of the default settings, but for some reason all the check boxes are checked under  the "Bastion Autosplitter" tab. I have unchecked both "Split after the Sole Regret" and "Split Tazal I".

Thanks again.

**Comment by Synthian** [comment]
Pending further investigation

**Comment by Rugbeo** [comment]
Following these steps resolved the default settings issue for me:

1. Remove the autosplitter from the layout in LiveSplit
2. Save the layout change and close LiveSplit
3. Remove the .dll from the Components folder
4. Download a fresh copy of the .dll from the Releases page
5. Add the fresh .dll to the Components folder
6. Add the autosplitter back to the layout.
