### ISSUE TITLE
Run Ends too Soon

### ISSUE THREAD

**Issue by Rugbeo** [Synthian/LiveSplit.Bastion#3]
Hello!

The autosplitter appears to end the run after I speak with the stranger in the heart of the bastion.

Thank you!

**Comment by Synthian** [comment]
Hey, this shouldn't be happening unless you select a dialogue option from The Stranger or Zia. (Which you don't need to do to end the game, you just have to talk to them and close the dialogue options.) Is that what you did?

**Comment by Rugbeo** [comment]
Yep, that was my fault. Should add some extra time savings in my runs now too :)

Thanks for the prompt response.
