### ISSUE TITLE
Livesplit reports that "There is no Auto Splitter available for this game"

### ISSUE THREAD

**Issue by BasedJellyfish11** [Synthian/LiveSplit.Bastion#9]
Current

![image](https://user-images.githubusercontent.com/42121314/43689022-f015a60a-98f3-11e8-92fc-414ca4690e57.png)

Wanted

![image](https://user-images.githubusercontent.com/42121314/43689027-085e37d6-98f4-11e8-81cf-61c0ded0cbcc.png)

**Comment by Synthian** [comment]
I've created a pull request to get the auto splitter registered with LiveSplit - now pending their approval

**Comment by Synthian** [comment]
This is now the primary way to get access to the auto splitter, thanks acrid!
